semaine5/api_SSBU/src/Entity/Personnage.php
<?php

namespace App\Entity;

use App\Repository\PersonnageRepository;
use App\Entity\Univers;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

/**
 * @ORM\Entity(repositoryClass=PersonnageRepository::class)
 */
class Personnage implements JsonSerializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $link_image;

    /**
     * @ORM\ManyToOne(targetEntity=univers::class, inversedBy="personnages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idUnivers;

    /**
     * @ORM\OneToMany(targetEntity=CoupSpeciaux::class, mappedBy="idPersonnage")
     */
    private $coupSpeciauxes;

    /**
     * @ORM\OneToMany(targetEntity=Combat::class, mappedBy="personnage_joueur")
     */
    private $combats;

    public function __construct()
    {
        $this->coupSpeciauxes = new ArrayCollection();
        $this->combats = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLinkImage(): ?string
    {
        return $this->link_image;
    }

    public function setLinkImage(string $link_image): self
    {
        $this->link_image = $link_image;

        return $this;
    }

    public function getIdUnivers(): ?univers
    {
        return $this->idUnivers;
    }

    public function setIdUnivers(?univers $idUnivers): self
    {
        $this->idUnivers = $idUnivers;

        return $this;
    }

    /**
     * @return Collection|CoupSpeciaux[]
     */
    public function getCoupSpeciauxes(): Collection
    {
        return $this->coupSpeciauxes;
    }

    public function addCoupSpeciaux(CoupSpeciaux $coupSpeciaux): self
    {
        if (!$this->coupSpeciauxes->contains($coupSpeciaux)) {
            $this->coupSpeciauxes[] = $coupSpeciaux;
            $coupSpeciaux->setIdPersonnage($this);
        }

        return $this;
    }

    public function removeCoupSpeciaux(CoupSpeciaux $coupSpeciaux): self
    {
        if ($this->coupSpeciauxes->removeElement($coupSpeciaux)) {
            // set the owning side to null (unless already changed)
            if ($coupSpeciaux->getIdPersonnage() === $this) {
                $coupSpeciaux->setIdPersonnage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Combat[]
     */
    public function getCombats(): Collection
    {
        return $this->combats;
    }

    public function addCombat(Combat $combat): self
    {
        if (!$this->combats->contains($combat)) {
            $this->combats[] = $combat;
            $combat->setPersonnageJoueur($this);
        }

        return $this;
    }

    public function removeCombat(Combat $combat): self
    {
        if ($this->combats->removeElement($combat)) {
            // set the owning side to null (unless already changed)
            if ($combat->getPersonnageJoueur() === $this) {
                $combat->setPersonnageJoueur(null);
            }
        }

        return $this;
    }

    public function jsonPersonnages(){

        $personnagesArray = [];
        foreach($this->personnages as $personnage){
            $personnagesArray[] = $personnage->jsonSerialize();
        }
        return $personnagesArray;
    }

    public function jsonSerialize()
    {
        return
        [
            'id' => $this->getId(),
            'name'  => $this->getName(),
            'link_image'  => $this->getLinkImage(),
            'personnages'  => $this->jsonPersonnages(),
        ];
    }

    public function jsonSerializeList()
    {
        return
        [
            'id' => $this->getId(),
            'name'  => $this->getName(),
            'link_image'  => $this->getLinkImage(),
            //'personnagesCount'  => count($this->personnages),
        ];
    }
}

semaine5/api_SSBU/src/Form/PersonnageType.php
<?php

namespace App\Form;

use App\Entity\Personnage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonnageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('link_image')
            ->add('idUnivers')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personnage::class,
        ]);
    }
}

semaine5/api_SSBU/src/Controller/PersonnageController.php
<?php

namespace App\Controller;

use App\Entity\Personnage;
use App\Form\PersonnageType;
use App\Repository\PersonnageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/personnage")
 */
class PersonnageController extends AbstractController
{
    /**
     * @Route("/", name="personnage_index", methods={"GET"})
     */
    public function index(PersonnageRepository $personnageRepository): Response
    {
        $personnages = [];
        foreach($personnageRepository->findAll() as $personnage){
            $personnages[] = $personnage->jsonSerializeList();
        }

        return new JsonResponse([
            "data" => $personnages
        ]);
        //return $this->render('personnage/index.html.twig', [
        //    'personnages' => $personnageRepository->findAll(),
        //]);
    }

    /**
     * @Route("/new", name="personnage_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $personnage = new Personnage();
        $form = $this->createForm(PersonnageType::class, $personnage);
        //$form->handleRequest($request);
        $form->submit(json_decode($request->getContent()));

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($personnage);
            $entityManager->flush();

            //return $this->redirectToRoute('personnage_index', [], Response::HTTP_SEE_OTHER);
            return new JsonResponse([
                "data" => $auteur
            ], 201);
        }

        else{
            $errors = [];
            // Global
            foreach ($form->getErrors() as $error) {
                $errors[$form->getName()][] = $error->getMessage();
            }
            
            // Fields
            foreach ($form as $child /** @var Form $child */) {
                if (!$child->isValid()) {
                    foreach ($child->getErrors() as $error) {
                        $errors[$child->getName()][] = $error->getMessage();
                    }
                }
            }
            
            return new JsonResponse([
                'erorrs' => $errors,
            ], 400);  
        }

        //return $this->renderForm('personnage/new.html.twig', [
        //    'personnage' => $personnage,
        //    'form' => $form,
        //]);
    }

    /**
     * @Route("/{id}", name="personnage_show", methods={"GET"})
     */
    public function show(Personnage $personnage): Response
    {
        return $this->render('personnage/show.html.twig', [
            'personnage' => $personnage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="personnage_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Personnage $personnage, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PersonnageType::class, $personnage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('personnage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personnage/edit.html.twig', [
            'personnage' => $personnage,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="personnage_delete", methods={"POST"})
     */
    public function delete(Request $request, Personnage $personnage, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personnage->getId(), $request->request->get('_token'))) {
            $entityManager->remove($personnage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('personnage_index', [], Response::HTTP_SEE_OTHER);
    }
}

semaine5/api_SSBU/templates/personnage/_delete_form.html.twig
<form method="post" action="{{ path('personnage_delete', {'id': personnage.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personnage.id) }}">
    <button class="btn">Delete</button>
</form>

semaine5/api_SSBU/templates/personnage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

semaine5/api_SSBU/templates/personnage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Personnage{% endblock %}

{% block body %}
    <h1>Edit Personnage</h1>

    {{ include('personnage/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('personnage_index') }}">back to list</a>

    {{ include('personnage/_delete_form.html.twig') }}
{% endblock %}

semaine5/api_SSBU/templates/personnage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnage index{% endblock %}

{% block body %}
    <h1>Personnage index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Link_image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personnage in personnages %}
            <tr>
                <td>{{ personnage.id }}</td>
                <td>{{ personnage.name }}</td>
                <td>{{ personnage.linkImage }}</td>
                <td>
                    <a href="{{ path('personnage_show', {'id': personnage.id}) }}">show</a>
                    <a href="{{ path('personnage_edit', {'id': personnage.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('personnage_new') }}">Create new</a>
{% endblock %}

semaine5/api_SSBU/templates/personnage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Personnage{% endblock %}

{% block body %}
    <h1>Create new Personnage</h1>

    {{ include('personnage/_form.html.twig') }}

    <a href="{{ path('personnage_index') }}">back to list</a>
{% endblock %}

semaine5/api_SSBU/templates/personnage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnage{% endblock %}

{% block body %}
    <h1>Personnage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personnage.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ personnage.name }}</td>
            </tr>
            <tr>
                <th>Link_image</th>
                <td>{{ personnage.linkImage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('personnage_index') }}">back to list</a>

    <a href="{{ path('personnage_edit', {'id': personnage.id}) }}">edit</a>

    {{ include('personnage/_delete_form.html.twig') }}
{% endblock %}