semaine5/api_SSBU/src/Entity/Combat.php
<?php

namespace App\Entity;

use App\Repository\CombatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CombatRepository::class)
 */
class Combat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="smallint")
     */
    private $a_gagner;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $adversaire;

    /**
     * @ORM\ManyToOne(targetEntity=Personnage::class, inversedBy="combats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personnage_joueur;

    /**
     * @ORM\ManyToOne(targetEntity=personnage::class, inversedBy="combats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $personnage_adversaire;

    public function __toString()
    {
        return $this->date;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAGagner(): ?int
    {
        return $this->a_gagner;
    }

    public function setAGagner(int $a_gagner): self
    {
        $this->a_gagner = $a_gagner;

        return $this;
    }

    public function getAdversaire(): ?string
    {
        return $this->adversaire;
    }

    public function setAdversaire(string $adversaire): self
    {
        $this->adversaire = $adversaire;

        return $this;
    }

    public function getPersonnageJoueur(): ?Personnage
    {
        return $this->personnage_joueur;
    }

    public function setPersonnageJoueur(?Personnage $personnage_joueur): self
    {
        $this->personnage_joueur = $personnage_joueur;

        return $this;
    }

    public function getPersonnageAdversaire(): ?personnage
    {
        return $this->personnage_adversaire;
    }

    public function setPersonnageAdversaire(?personnage $personnage_adversaire): self
    {
        $this->personnage_adversaire = $personnage_adversaire;

        return $this;
    }
}

semaine5/api_SSBU/src/Form/CombatType.php
<?php

namespace App\Form;

use App\Entity\Combat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CombatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('a_gagner')
            ->add('adversaire')
            ->add('personnage_joueur')
            ->add('personnage_adversaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Combat::class,
        ]);
    }
}

semaine5/api_SSBU/src/Controller/CombatController.php
<?php

namespace App\Controller;

use App\Entity\Combat;
use App\Form\CombatType;
use App\Repository\CombatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/combat")
 */
class CombatController extends AbstractController
{
    /**
     * @Route("/", name="combat_index", methods={"GET"})
     */
    public function index(CombatRepository $combatRepository): Response
    {
        return $this->render('combat/index.html.twig', [
            'combats' => $combatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="combat_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $combat = new Combat();
        $form = $this->createForm(CombatType::class, $combat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($combat);
            $entityManager->flush();

            return $this->redirectToRoute('combat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('combat/new.html.twig', [
            'combat' => $combat,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="combat_show", methods={"GET"})
     */
    public function show(Combat $combat): Response
    {
        return $this->render('combat/show.html.twig', [
            'combat' => $combat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="combat_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Combat $combat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CombatType::class, $combat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('combat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('combat/edit.html.twig', [
            'combat' => $combat,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="combat_delete", methods={"POST"})
     */
    public function delete(Request $request, Combat $combat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$combat->getId(), $request->request->get('_token'))) {
            $entityManager->remove($combat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('combat_index', [], Response::HTTP_SEE_OTHER);
    }
}

semaine5/api_SSBU/templates/combat/_delete_form.html.twig
<form method="post" action="{{ path('combat_delete', {'id': combat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ combat.id) }}">
    <button class="btn">Delete</button>
</form>

semaine5/api_SSBU/templates/combat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

semaine5/api_SSBU/templates/combat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Combat{% endblock %}

{% block body %}
    <h1>Edit Combat</h1>

    {{ include('combat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('combat_index') }}">back to list</a>

    {{ include('combat/_delete_form.html.twig') }}
{% endblock %}

semaine5/api_SSBU/templates/combat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Combat index{% endblock %}

{% block body %}
    <h1>Combat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>A_gagner</th>
                <th>Adversaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for combat in combats %}
            <tr>
                <td>{{ combat.id }}</td>
                <td>{{ combat.date ? combat.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ combat.aGagner }}</td>
                <td>{{ combat.adversaire }}</td>
                <td>
                    <a href="{{ path('combat_show', {'id': combat.id}) }}">show</a>
                    <a href="{{ path('combat_edit', {'id': combat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('combat_new') }}">Create new</a>
{% endblock %}

semaine5/api_SSBU/templates/combat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Combat{% endblock %}

{% block body %}
    <h1>Create new Combat</h1>

    {{ include('combat/_form.html.twig') }}

    <a href="{{ path('combat_index') }}">back to list</a>
{% endblock %}

semaine5/api_SSBU/templates/combat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Combat{% endblock %}

{% block body %}
    <h1>Combat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ combat.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ combat.date ? combat.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>A_gagner</th>
                <td>{{ combat.aGagner }}</td>
            </tr>
            <tr>
                <th>Adversaire</th>
                <td>{{ combat.adversaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('combat_index') }}">back to list</a>

    <a href="{{ path('combat_edit', {'id': combat.id}) }}">edit</a>

    {{ include('combat/_delete_form.html.twig') }}
{% endblock %}